apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorang-backend-deploy-prod
  labels:
    app: memorang-backend-prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: memorang-backend-prod
  template:
    metadata:
      labels:
        app: memorang-backend-prod
    spec:
      nodeSelector:
        node-type: regular
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: memorang-backend-prod
        image: tickertom.azurecr.io/memorang-backend:latest
        imagePullPolicy: Always
        env:
        - name: DOPPLER_TOKEN
          valueFrom:
            secretKeyRef:
              name: doppler-tokens
              key: BACKEND_DOPPLER_TOKEN
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3001"
        ports:
        - containerPort: 3001
          name: mem-api-port
