apiVersion: v1
kind: Service
metadata:
  name: memorang-backend
  namespace: memorang
spec:
  selector:
    app: memorang-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
