apiVersion: v1
kind: Secret
metadata:
  name: doppler-tokens
  namespace: memorang
type: Opaque
stringData:
  FRONTEND_DOPPLER_TOKEN: "dp.st.example_frontend_token"
  BACKEND_DOPPLER_TOKEN: "dp.st.example_backend_token"
  WORKER_DOPPLER_TOKEN: "dp.st.example_worker_token"
