apiVersion: v1
kind: Service
metadata:
  name: memorang-frontend
  namespace: memorang
spec:
  selector:
    app: memorang-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
