apiVersion: v1
kind: Service
metadata:
  name: memorang-frontend-svc-prod
spec:
  selector:
    app: memorang-frontend-prod
  ports:
  - name: mem-fe-svc-port
    protocol: TCP
    port: 80
    targetPort: mem-fe-pod-port
